services:
  todos.api:
    image: ${DOCKER_REGISTRY-}todos
    build:
      context: .
      dockerfile: Todos/Dockerfile
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports: 
      - 8080:8080
    depends_on:
      database:
        condition: service_started
  database:
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      MSSQL_SA_PASSWORD: "Aa@123456789"
      ACCEPT_EULA: "1"
    volumes:
     - database.volume:/var/opt/mssql
    ports:
      - "1434:1433"
    networks: 
      - default.network
    restart: always

volumes:
  database.volume: